version: "3.9"

services:
  api:
    build:
      context: ./api
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    env_file:
      - .env.dev
    command: >
      sh -c " python manage.py wait_for_db &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  frontend:
    build:
      context: ./apple-a-day-fe
    volumes:
      - ./fe:/fe
      - /fe/node_modules
    env_file:
      - .env.fe
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
  db:
    image: postgres:alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - .env.db
volumes:
  dev-db-data:
