version: "3.9"

services:
  api:
    build:
      context: ./api
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    networks:
      - apple-a-day
    env_file:
      - .env.dev
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  frontend:
      build:
        context: ./apple-a-day-fe
      volumes:
        - ./apple-a-day-fe:/fe
      networks:
        - apple-a-day
      env_file:
        - .env.fe
      ports:
        - "3000:3000"
      environment:
        - CHOKIDAR_USEPOLLING=true
networks:
  apple-a-day:
    driver: bridge
