# Generated by Django 5.0.6 on 2024-06-26 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellbeing', models.IntegerField(help_text='Enter a value from 1 (very unwell) to 10 (extremely well)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mental_stress', models.IntegerField(help_text='Enter a value from 1 (no stress) to 10 (extremely stressed)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('physical_stress', models.IntegerField(help_text='Enter a value from 1 (no stress) to 10 (extremely stressed)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
