# Generated by Django 5.0.6 on 2024-07-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0003_tag_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
