name: CI

on: [push]

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DEV: ${{ secrets.DEV }}
  ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}



jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: docker-compose -f docker-compose.prod.yml run --rm api sh -c "ruff check . --fix"
      - name: Test
        run: docker-compose -f docker-compose.prod.yml run --rm api sh -c "python manage.py wait_for_db && python manage.py test"
